In [1]:
import sqlite3
from pandas import read_sql_query
from pymongo import MongoClient

In [2]:
def read_sqlite(dbfile):
    with sqlite3.connect(dbfile) as dbcon:
        tables = list(read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", dbcon)['name'])
        out = {tbl : read_sql_query(f"SELECT * from {tbl}", dbcon) for tbl in tables}
    return out

In [3]:
db = read_sqlite('love4pets.db')
db

{'departamento':    departamento_id            nombre
 0                1          finanzas
 1                2            ventas
 2                3  recursos humanos
 3                4         marketing
 4                5       veterinario
 5                6       informatica
 6                7     investigacion,
 'cliente':     cliente_id                   nombre                   email   telefono  \
 0            1    Mario Flores Gallardo   marioflores@gmail.com  036-15-36
 1            2      Arnau Medina Garcia   arnaumedina@gmail.com  094-10-88
 2            3        Ivan Medina Rubio    ivanmedina@gmail.com  083-08-72
 3            4       Jan Vargas Santana     vargasjan@gmail.com  780-65-24
 4            5    Carlos Costa Guerrero  carloscostag@gmail.com  180-65-24
 5            6    Roberto Martin Ortega  robertmartin@gmail.com  742-63-27
 6            7  Gabriel Gonzalez Ortega     gabogonzo@gmail.com  780-13-14
 7            8        Rayan Leon Ferrer        rayito@gmail.com  430-65-24
 8            9       Aitor Ruiz Sanchez  aitorsanchez@gmail.com  780-77-24
 9           10      Eric Rubio Carrasco     ericrubio@gmail.com  780-65-79
 10          11        Alberto Sanz Ruiz        albert@gmail.com  781-15-24
 11          12   Jesus Medina Hernandez      jmedinah@gmail.com  782-35-25
 12          13            Pol Moya Pena       polmoya@gmail.com  780-25-24
 13          14  Jose Gallardo Rodriguez  josegallardo@gmail.com  783-65-11
 14          15         Manuel Angel Gil        manano@gmail.com  733-65-16

                      contacto telefono_contacto  ciudad
 0   Aintzane Alvarez Iglesias         210-35-57  Madrid
 1                                                Madrid
 2             Javier Domenech         488-48-46  Toledo
 3                                                Madrid
 4            Cristian Jimenez         801-28-09  Madrid
 5         Jorge Vila Gallardo         564-52-13  Madrid
 6          Miguel Bosch Parra         882-17-20  Madrid
 7        Santiago Perez Ramos         577-21-24  Madrid
 8     Gabriel Gonzalez Ortega         784-96-31  Madrid
 9   Cristian Jimenez Martinez         147-01-12  Madrid
 10    Gabriel Gonzalez Ortega         028-51-21  Madrid
 11    Vctor Gonzalez Castillo         661-85-12  Madrid
 12                                               Toledo
 13      Hector Martin Morales         867-97-99  Madrid
 14             Hector Navarro         067-97-91  Madrid  ,
 'mascota':    mascota_id  nombre  cliente_id especie           raza      fecha_nacimiento
 0           1    Luna           2    gato        mestizo  2009-01-01 00:00:000
 1           2    Sole           3    gato        mestizo  2010-02-01 00:00:000
 2           3    Mida           3   perro  Caint terrier  2007-02-03 00:00:000
 3           4    Tara           5   perro         Puddle  2006-02-03 00:00:000
 4           5  Pelusa           6   perro         Puddle  2008-02-03 00:00:000
 5           6   irene           7    gato         siames  2015-02-03 00:00:000
 6           7    sara           8    gato        mestizo  2016-05-01 00:00:000
 7           8    milo          11    gato        mestizo  2016-09-01 00:00:000
 8           9  oliver          11    gato        mestizo  2016-07-07 00:00:000
 9          10    Duke          14   perro  Pastor Aleman  2011-05-03 00:00:000,
 'producto':    producto_id           nombre                   descripcion  precio
 0            1  Champu Mimadito   Champu neutro para mascotas       7
 1            2        Vitaminas        Complemento vitaminico       5
 2            3       Antipulgas            Liquido antipulgas       3
 3            4        Perrarina                        Huesos      12
 4            5         Gatarina                   Catspettito      13
 5            6         Peine N7    Peine para perros numero 7       3
 6            7       peluqueria  Corte de cabello para perros       3
 7            8         Consulta          Consulta veterinaria      15,
 'orden':     orden_id  cliente_id                 fecha
 0          1           2  2017-01-01 00:00:000
 1          2           1  2018-02-01 00:00:000
 2          3           2  2016-03-01 00:00:000
 3          4           3  2016-04-01 00:00:000
 4          5           4  2017-05-01 00:00:000
 5          6           5  2016-06-01 00:00:000
 6          7          11  2017-07-01 00:00:000
 7          8           2  2017-01-01 00:00:000
 8          9           6  2018-08-01 00:00:000
 9         10           2  2017-01-01 00:00:000
 10        11           6  2017-09-01 00:00:000
 11        12          12  2018-01-01 00:00:000
 12        13           2  2017-01-11 00:00:000
 13        14           7  2018-01-01 00:00:000
 14        15           9  2017-01-13 00:00:000
 15        16           2  2015-01-01 00:00:000
 16        17           8  2017-01-01 00:00:000
 17        18           2  2014-01-01 00:00:000
 18        19          13  2016-01-01 00:00:000
 19        20           2  2017-01-01 00:00:000
 20        21          10  2015-01-01 00:00:000
 21        22          11  2017-01-01 00:00:000
 22        23          14  2011-01-01 00:00:000
 23        24           3  2017-01-01 00:00:000,
 'detalle_orden':     detalle_id  orden_id  producto_id  cantidad  precio
 0            1         1            1         2       7
 1            2         1            3         2       3
 2            3         1            5         1      13
 3            4         2            3         3       3
 4            5         2            5         1      13
 5            6         3            8         2      15
 6            7         4            5         1      13
 7            8         5            8         1      15
 8            9         6            5         2      13
 9           10         7            4         3      12
 10          11         8            5         1      13
 11          12         8            2         3       5
 12          13         9            5         1      13
 13          14        10            3         2      33
 14          15        11            7         1       3
 15          16        12            2         3       5
 16          17        13            7         1       3
 17          18        13            5         2      13
 18          19        14            2         3       5
 19          20        14            7         1       3
 20          21        15            5         1      13
 21          22        16            2         3       5
 22          23        17            7         1       3
 23          24        18            5         1      13
 24          25        19            2         3       5
 25          26        20            5         4      13
 26          27        21            5         1      13
 27          28        22            2         3       5
 28          29        22            5         1      13
 29          30        23            7         1       3
 30          31        24            2         3       5
 31          32        24            5         1      13
 32          33        24            7         1       3,
 'proveedor':    proveedor_id              nombre                        email    telefono
 0             1           Pets prov           petsprov@gmail.com   818853151
 1             2             maxipet            maxipet@gmail.com  8650001508
 2             3  adorables mascotas  adorablesmascotas@gmail.com  7150383416
 3             4            huesitos           huesitos@gmail.com  6640163977,
 'suministro':    proveedor_id  producto_id  cantidad                 fecha
 0             3            1        30  2015-01-01 00:00:000
 1             3            2        10  2015-01-01 00:00:000
 2             2            3         5  2015-01-01 00:00:000
 3             2            4         5  2015-01-01 00:00:000
 4             1            5         5  2015-01-01 00:00:000
 5             4            6         5  2015-01-01 00:00:000,
 'empleado':     empleado_id                    nombre                        email  \
 0             1      Andres Riera Herrera            andresr@gmail.com
 1             2   Lucas Serrano Caballero            lucas99@gmail.com
 2             3           Pablo Pons Sanz             ppsanz@gmail.com
 3             4        Saul Moreno Santos  saul.morenosantos@gmail.com
 4             5            Nil Soler Diez           nilsoler@gmail.com
 5             6     Sergio Reyes Gallardo               zerg@gmail.com
 6             7       Isaac Jimenez Ortiz         isaacortiz@gmail.com
 7             8     Guillermo Vidal Gomez        guillevidal@gmail.com
 8             9  Daniel Quintero Quintero   danielquinterox2@gmail.com
 9            10      Juan Manuel Olivares             juanma@gmail.com
 10           11               Miguel Soto             misoto@gmail.com
 11           12       Alejandro Fernandez             alefer@gmail.com

      telefono  salario         fecha_ingreso  departamento_id
 0   200-88-76     1500  2017-05-17 00:00:000              6.0
 1   115-24-36     1200  2018-05-17 00:00:000              2.0
 2   748-72-75     1350  2016-07-01 00:00:000              1.0
 3   346-87-27     1600  2016-07-01 00:00:000              1.0
 4   576-84-28     1100  2016-04-03 00:00:000              5.0
 5   598-95-67     1000  2016-04-03 00:00:000              5.0
 6   370-19-65     1600  2016-07-08 00:00:000              3.0
 7   099-05-68     1400  2016-01-03 00:00:000              3.0
 8   261-97-06     1500  2017-03-05 00:00:000              6.0
 9   269-37-06     1500  2017-03-05 00:00:000              NaN
 10  269-92-06     1900  2017-03-05 00:00:000              6.0
 11  119-91-16     1850  2017-03-05 00:00:000              6.0  }

In [4]:
db.keys()

dict_keys(['departamento', 'cliente', 'mascota', 'producto', 'orden', 'detalle_orden', 'proveedor', 'suministro', 'empleado'])

In [5]:
len(db)

9

In [6]:
db['departamento']

   departamento_id            nombre
0                1          finanzas
1                2            ventas
2                3  recursos humanos
3                4         marketing
4                5       veterinario
5                6       informatica
6                7     investigacion

In [7]:
db['departamento'].to_dict()

{'departamento_id': {0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7},
 'nombre': {0: 'finanzas',
  1: 'ventas',
  2: 'recursos humanos',
  3: 'marketing',
  4: 'veterinario',
  5: 'informatica',
  6: 'investigacion'}}

In [8]:
db['cliente'].to_dict()

{'cliente_id': {0: 1,
  1: 2,
  2: 3,
  3: 4,
  4: 5,
  5: 6,
  6: 7,
  7: 8,
  8: 9,
  9: 10,
  10: 11,
  11: 12,
  12: 13,
  13: 14,
  14: 15},
 'nombre': {0: 'Mario Flores Gallardo',
  1: 'Arnau Medina Garcia',
  2: 'Ivan Medina Rubio',
  3: 'Jan Vargas Santana',
  4: 'Carlos Costa Guerrero',
  5: 'Roberto Martin Ortega',
  6: 'Gabriel Gonzalez Ortega',
  7: 'Rayan Leon Ferrer',
  8: 'Aitor Ruiz Sanchez',
  9: 'Eric Rubio Carrasco',
  10: 'Alberto Sanz Ruiz',
  11: 'Jesus Medina Hernandez',
  12: 'Pol Moya Pena',
  13: 'Jose Gallardo Rodriguez',
  14: 'Manuel Angel Gil'},
 'email': {0: 'marioflores@gmail.com',
  1: 'arnaumedina@gmail.com',
  2: 'ivanmedina@gmail.com',
  3: 'vargasjan@gmail.com',
  4: 'carloscostag@gmail.com',
  5: 'robertmartin@gmail.com',
  6: 'gabogonzo@gmail.com',
  7: 'rayito@gmail.com',
  8: 'aitorsanchez@gmail.com',
  9: 'ericrubio@gmail.com',
  10: 'albert@gmail.com',
  11: 'jmedinah@gmail.com',
  12: 'polmoya@gmail.com',
  13: 'josegallardo@gmail.com',
  14: 'manano@gmail.com'},
 'telefono': {0: '036-15-36',
  1: '094-10-88',
  2: '083-08-72',
  3: '780-65-24',
  4: '180-65-24',
  5: '742-63-27',
  6: '780-13-14',
  7: '430-65-24',
  8: '780-77-24',
  9: '780-65-79',
  10: '781-15-24',
  11: '782-35-25',
  12: '780-25-24',
  13: '783-65-11',
  14: '733-65-16'},
 'contacto': {0: 'Aintzane Alvarez Iglesias',
  1: '',
  2: 'Javier Domenech',
  3: '',
  4: 'Cristian Jimenez',
  5: 'Jorge Vila Gallardo',
  6: 'Miguel Bosch Parra',
  7: 'Santiago Perez Ramos',
  8: 'Gabriel Gonzalez Ortega',
  9: 'Cristian Jimenez Martinez',
  10: 'Gabriel Gonzalez Ortega',
  11: 'Vctor Gonzalez Castillo',
  12: '',
  13: 'Hector Martin Morales',
  14: 'Hector Navarro'},
 'telefono_contacto': {0: '210-35-57',
  1: '',
  2: '488-48-46',
  3: '',
  4: '801-28-09',
  5: '564-52-13',
  6: '882-17-20',
  7: '577-21-24',
  8: '784-96-31',
  9: '147-01-12',
  10: '028-51-21',
  11: '661-85-12',
  12: '',
  13: '867-97-99',
  14: '067-97-91'},
 'ciudad': {0: 'Madrid',
  1: 'Madrid',
  2: 'Toledo',
  3: 'Madrid',
  4: 'Madrid',
  5: 'Madrid',
  6: 'Madrid',
  7: 'Madrid',
  8: 'Madrid',
  9: 'Madrid',
  10: 'Madrid',
  11: 'Madrid',
  12: 'Toledo',
  13: 'Madrid',
  14: 'Madrid'}}

In [9]:
db["cliente"]

,cliente_id,nombre,email,telefono,contacto,telefono_contacto,ciudad
0,1,Mario Flores Gallardo,marioflores@gmail.com,036-15-36,Aintzane Alvarez Iglesias,210-35-57,Madrid
1,2,Arnau Medina Garcia,arnaumedina@gmail.com,094-10-88,,,Madrid
2,3,Ivan Medina Rubio,ivanmedina@gmail.com,083-08-72,Javier Domenech,488-48-46,Toledo
3,4,Jan Vargas Santana,vargasjan@gmail.com,780-65-24,,,Madrid
4,5,Carlos Costa Guerrero,carloscostag@gmail.com,180-65-24,Cristian Jimenez,801-28-09,Madrid
5,6,Roberto Martin Ortega,robertmartin@gmail.com,742-63-27,Jorge Vila Gallardo,564-52-13,Madrid
6,7,Gabriel Gonzalez Ortega,gabogonzo@gmail.com,780-13-14,Miguel Bosch Parra,882-17-20,Madrid
7,8,Rayan Leon Ferrer,rayito@gmail.com,430-65-24,Santiago Perez Ramos,577-21-24,Madrid
8,9,Aitor Ruiz Sanchez,aitorsanchez@gmail.com,780-77-24,Gabriel Gonzalez Ortega,784-96-31,Madrid
9,10,Eric Rubio Carrasco,ericrubio@gmail.com,780-65-79,Cristian Jimenez Martinez,147-01-12,Madrid
10,11,Alberto Sanz Ruiz,albert@gmail.com,781-15-24,Gabriel Gonzalez Ortega,028-51-21,Madrid
11,12,Jesus Medina Hernandez,jmedinah@gmail.com,782-35-25,Vctor Gonzalez Castillo,661-85-12,Madrid
12,13,Pol Moya Pena,polmoya@gmail.com,780-25-24,,,Toledo
13,14,Jose Gallardo Rodriguez,josegallardo@gmail.com,783-65-11,Hector Martin Morales,867-97-99,Madrid
14,15,Manuel Angel Gil,manano@gmail.com,733-65-16,Hector Navarro,067-97-91,Madrid